apiVersion: apps/v1
kind: Deployment
metadata:
  name: giropops-senhas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: giropops-senhas
  template:    
    metadata:
      labels:
        app: giropops-senhas
    spec:
      containers:
      - name: giropops-senhas
        image: ferpdias/linuxtips-giropops-senhas:1.0
        env:
        - name: REDIS_HOST
          value: redis
        ports:
        - containerPort: 5000
          name: giropops-senhas
        resources:
          limits: 
            # Limitar bastante o uso de CPU e memória para a criação de Pods pelo HPA
            cpu: 50m
            memory: 75Mi
---
apiVersion: v1
kind: Service
metadata:
  name: giropops-senhas
spec:
  selector:
    app: giropops-senhas
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30100
  type: NodePort